---
title: "Cap 4 - Figura 25"
author: "Aishameriane Schmidt"
date: "1 de abril de 2018"
output: html_document
bibliography: references.bib
---

Este código gera a figura 25 das notas de aula.

# Carregando os pacotes

```{r, message = FALSE, warning = FALSE}
chooseCRANmirror(graphics = FALSE, ind = 10)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, gridExtra, latex2exp, RColorBrewer, ggfortify)
``` 

# Exemplo 4.4.4 (retirado de [@casella_MC])

Considere a cadeia de Markov definida por $X^{(t+1)} = \rho X^{(t)} + \epsilon_t$, com $\epsilon_t \sim \mathcal{N}(0,1)$. Simule $X^{(0)} \sim \mathcal{N}(0,1)$ e plote o histograma de uma amostra de $X^{(t)}$ para $t \leq 10^4$ e $\rho = 0.9$. Verifique a aderência da distribuição estacionária $\mathcal{N}\left(0,\frac{1}{(1-\rho^2)}\right)$.

```{r}
# Define a semente
set.seed(6969)

# Define o t máximo
tamanho <- 10^4

# Define o valor de rho
rho <- 0.9

# Amostra o valor inicial
X_0 <- rnorm(0,1,n = 1)

# Cria uma cadeia vazia
cadeia <- vector()
cadeia[1] <- X_0

# Popula a cadeia
for (i in 2:tamanho){
  cadeia[i] <- rho*cadeia[i-1]+rnorm(0,1,n=1)
}

cores <- brewer.pal(6, "Dark2")
cores2 <- brewer.pal(10, "Paired")
cadeiadf <- data.frame(1:tamanho, cadeia)

# Plot os the time series
p1 <- autoplot(as.ts(cadeia), main = "Evolução dos dados ao longo do tempo", xlab = "Tempo", ylab = TeX('X^{(t+1)}'), colour = cores2[10]) +  
  theme(plot.title=element_text(size = 12),
              text=element_text(size = 12),
              axis.text.x=element_text(colour="black", size = 10),
              axis.text.y=element_text(colour="black", size = 10),
              panel.background = element_blank(),
              panel.grid.major = element_line(colour = "gray"),
              panel.grid.minor = element_line(),
              panel.border = element_rect(colour = "black", fill = NA))

# Histogram overlaid with kernel density curve
p2 <- ggplot(cadeiadf, aes(x=cadeiadf$cadeia)) + 
    geom_histogram(aes(y=..density..),      # Histogram with density instead of count on y-axis
                   binwidth=.5, fill = cores[3], colour = cores[3], alpha=0.5)+
   stat_function(
     fun = function(x, mean, sd, n, bw){
       dnorm(x =x, mean = mean, sd = sd)
   },
   args = c(mean = 0, sd = 1/sqrt(1-rho^2), n = length(cadeia), bw = .5), colour = cores2[10], size = 1)+
  labs(title= TeX('Simulando $X^{(t+1)}=\\rho X^{(t)} + \\epsilon_t$, $\\epsilon_t \\sim N(0,1)$, $\\rho = .9$'), y = "", x= TeX('$X^{(t+1)}$'), color = "Variável") +
    theme(plot.title=element_text(size = 12),
              text=element_text(size = 12),
              axis.text.x=element_text(colour="black", size = 10),
              axis.text.y=element_text(colour="black", size = 10),
              panel.background = element_blank(),
              panel.grid.major = element_line(colour = "gray"),
              panel.grid.minor = element_line(),
              panel.border = element_rect(colour = "black", fill = NA))
p2 <- p2 + geom_vline(aes(xintercept=mean(cadeia)),
            color="purple", linetype="dashed", size=1) + annotate("text", x = 3.5, y = 0.17, label = paste0("Média dos\n valores simulados\n", round(mean(cadeia),4)), size = 2.5)

grid.arrange(p1, p2, ncol = 2, nrow = 1)

```